# Generated by Django 4.2.4 on 2023-11-08 06:43

from django.db import migrations


def set_age_group(apps, schema_editor):
    person = apps.get_model('main_app', 'Person')

    persons = person.objects.all()

    for p in persons:
        if p.age <= 12:
            p.age_group = 'Child'

        elif 12 < p.age < 18:
            p.age_group = 'Teen'

        else:
            p.age_group = 'Adult'

    person.objects.bulk_update(persons, ['age_group'])


def set_age_group_default(apps, schema_editor):
    person = apps.get_model('main_app', 'Person')

    persons = person.objects.all()

    age_group_default = person._meta.get_field('age_group').default

    for p in persons:
        p.age_group = age_group_default

    person.objects.bulk_update(persons, ['age_group'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group, reverse_code=set_age_group_default)
    ]
