# Generated by Django 4.2.4 on 2023-11-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_website_ulr_customer_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='website_url',
            field=models.URLField(error_messages='Enter a valid URL'),
        ),
    ]
